import { Injectable } from '@angular/core';

@Injectable()
export class ChartingService {

  constructor() { }

 private chartData = [
	{
		"CategoryID": 4,
		"CategoryName": "Dairy Products",
		"Description": "Cheeses",
		"ProductID": 60,
		"ProductName": "Camembert Pierrot",
		"SupplierID": 28,
		"QuantityPerUnit": "15 - 300 g rounds",
		"UnitPrice": 34,
		"UnitsInStock": 19,
		"UnitsOnOrder": 0,
		"ReorderLevel": 0,
		"Discontinued": false,
		"OrderID": 10252,
		"ProductName_Extended": "Camembert Pierrot",
		"UnitPrice_Extended": 45,
		"Quantity_Extended": 5,
		"Discount_Extended": 1,
		"ExtendedPrice": 0,
		"Subtotal": 0,
		"CompanyName": "Gai pâturage",
		"ContactName": "Eliane Noz",
		"ContactTitle": "Sales Representative",
		"Address": "Bat. B 3, rue des Alpes",
		"City": "Annecy",
		"PostalCode": "74000",
		"Country": "France",
		"Phone": "38.76.98.06",
		"Fax": "38.76.98.58"
	},
	{
		"CategoryID": 7,
		"CategoryName": "Produce",
		"Description": "Dried fruit and bean curd 1",
		"ProductID": 7,
		"ProductName": "Uncle Bob's Organic Dried Pears",
		"SupplierID": 3,
		"QuantityPerUnit": "12 - 1 lb pkgs.",
		"UnitPrice": 30,
		"UnitsInStock": 15,
		"UnitsOnOrder": 0,
		"ReorderLevel": 10,
		"Discontinued": false,
		"OrderID": 10385,
		"ProductName_Extended": "Uncle Bob's Organic Dried Pears",
		"UnitPrice_Extended": 24,
		"Quantity_Extended": 10,
		"Discount_Extended": 1,
		"ExtendedPrice": 0,
		"Subtotal": 64,
		"CompanyName": "Grandma Kelly's Homestead",
		"ContactName": "Regina Murphy",
		"ContactTitle": "Sales Representative",
		"Address": "707 Oxford Rd.",
		"City": "Ann Arbor",
		"Region": "MI",
		"PostalCode": "48104",
		"Country": "USA",
		"Phone": "(313) 555-5735",
		"Fax": "(313) 555-3349"
	},
	{
		"CategoryID": 4,
		"CategoryName": "Dairy Products",
		"Description": "Cheeses",
		"ProductID": 60,
		"ProductName": "Camembert Pierrot",
		"SupplierID": 28,
		"QuantityPerUnit": "15 - 300 g rounds",
		"UnitPrice": 34,
		"UnitsInStock": 19,
		"UnitsOnOrder": 0,
		"ReorderLevel": 0,
		"Discontinued": false,
		"OrderID": 10385,
		"ProductName_Extended": "Camembert Pierrot",
		"UnitPrice_Extended": 45,
		"Quantity_Extended": 5,
		"Discount_Extended": 1,
		"ExtendedPrice": 0,
		"Subtotal": 64,
		"CompanyName": "Gai pâturage",
		"ContactName": "Eliane Noz",
		"ContactTitle": "Sales Representative",
		"Address": "Bat. B 3, rue des Alpes",
		"City": "Annecy",
		"PostalCode": "74000",
		"Country": "France",
		"Phone": "38.76.98.06",
		"Fax": "38.76.98.58"
	},
	{
		"CategoryID": 3,
		"CategoryName": "Confections2",
		"Description": "Desserts, candies, and sweet breads 29",
		"ProductID": 68,
		"ProductName": "Scottish Longbreads",
		"SupplierID": 8,
		"QuantityPerUnit": "10 boxes x 8 pieces",
		"UnitPrice": 12.5,
		"UnitsInStock": 6,
		"UnitsOnOrder": 10,
		"ReorderLevel": 15,
		"Discontinued": false,
		"OrderID": 10385,
		"ProductName_Extended": "Scottish Longbreads",
		"UnitPrice_Extended": 10,
		"Quantity_Extended": 8,
		"Discount_Extended": 0.2,
		"ExtendedPrice": 64,
		"Subtotal": 64,
		"CompanyName": "Specialty Biscuits, Ltd.",
		"ContactName": "Peter Wilson",
		"ContactTitle": "Sales Representative",
		"Address": "29 King's Way",
		"City": "Manchester",
		"PostalCode": "M14 GSD",
		"Country": "UK",
		"Phone": "(161) 555-4448"
	},
	{
		"CategoryID": 1,
		"CategoryName": "Beverages",
		"Description": "Soft drinks, coffees, teas, beers, and ales",
		"ProductID": 24,
		"ProductName": "Guaraná Fantástica",
		"SupplierID": 10,
		"QuantityPerUnit": "12 - 355 ml cans",
		"UnitPrice": 4.5,
		"UnitsInStock": 20,
		"UnitsOnOrder": 0,
		"ReorderLevel": 0,
		"Discontinued": true,
		"OrderID": 10386,
		"ProductName_Extended": "Guaraná Fantástica",
		"UnitPrice_Extended": 3.6,
		"Quantity_Extended": 28,
		"Discount_Extended": 0,
		"ExtendedPrice": 100.8,
		"Subtotal": 212.8,
		"CompanyName": "Refrescos Americanas LTDA",
		"ContactName": "Carlos Diaz",
		"ContactTitle": "Marketing Manager",
		"Address": "Av. das Americanas 12.890",
		"City": "Sao Paulo",
		"PostalCode": "5442",
		"Country": "Brazil",
		"Phone": "(11) 555 4640"
	},
	{
		"CategoryID": 1,
		"CategoryName": "Beverages",
		"Description": "Soft drinks, coffees, teas, beers, and ales",
		"ProductID": 34,
		"ProductName": "Sasquatch Ale",
		"SupplierID": 16,
		"QuantityPerUnit": "24 - 12 oz bottles",
		"UnitPrice": 14,
		"UnitsInStock": 111,
		"UnitsOnOrder": 0,
		"ReorderLevel": 15,
		"Discontinued": false,
		"OrderID": 10386,
		"ProductName_Extended": "Sasquatch Ale",
		"UnitPrice_Extended": 11.2,
		"Quantity_Extended": 10,
		"Discount_Extended": 0,
		"ExtendedPrice": 112,
		"Subtotal": 212.8,
		"CompanyName": "Bigfoot Breweries",
		"ContactName": "Cheryl Saylor",
		"ContactTitle": "Regional Account Rep.",
		"Address": "3400 - 8th Avenue Suite 210",
		"City": "Bend",
		"Region": "OR",
		"PostalCode": "97101",
		"Country": "USA",
		"Phone": "(503) 555-9931"
	},
	{
		"CategoryID": 4,
		"CategoryName": "Dairy Products",
		"Description": "Cheeses",
		"ProductID": 31,
		"ProductName": "Gorgonzola Telino",
		"SupplierID": 14,
		"QuantityPerUnit": "12 - 100 g pkgs",
		"UnitPrice": 12.5,
		"UnitsInStock": 0,
		"UnitsOnOrder": 70,
		"ReorderLevel": 20,
		"Discontinued": false,
		"OrderID": 10390,
		"ProductName_Extended": "Gorgonzola Telino",
		"UnitPrice_Extended": 10,
		"Quantity_Extended": 60,
		"Discount_Extended": 0.1,
		"ExtendedPrice": 540,
		"Subtotal": 2090.88,
		"CompanyName": "Formaggi Fortini s.r.l.",
		"ContactName": "Elio Rossi",
		"ContactTitle": "Sales Representative",
		"Address": "Viale Dante, 75",
		"City": "Ravenna",
		"PostalCode": "48100",
		"Country": "Italy",
		"Phone": "(0544) 60323",
		"Fax": "(0544) 60603",
		"HomePage": "#FORMAGGI.HTM#"
	},
	{
		"CategoryID": 1,
		"CategoryName": "Beverages",
		"Description": "Soft drinks, coffees, teas, beers, and ales",
		"ProductID": 35,
		"ProductName": "Steeleye Stout",
		"SupplierID": 16,
		"QuantityPerUnit": "24 - 12 oz bottles",
		"UnitPrice": 18,
		"UnitsInStock": 20,
		"UnitsOnOrder": 0,
		"ReorderLevel": 15,
		"Discontinued": false,
		"OrderID": 10390,
		"ProductName_Extended": "Steeleye Stout",
		"UnitPrice_Extended": 14.4,
		"Quantity_Extended": 40,
		"Discount_Extended": 0.1,
		"ExtendedPrice": 518.4,
		"Subtotal": 2090.88,
		"CompanyName": "Bigfoot Breweries",
		"ContactName": "Cheryl Saylor",
		"ContactTitle": "Regional Account Rep.",
		"Address": "3400 - 8th Avenue Suite 210",
		"City": "Bend",
		"Region": "OR",
		"PostalCode": "97101",
		"Country": "USA",
		"Phone": "(503) 555-9931"
	},
	{
		"CategoryID": 8,
		"CategoryName": "Seafood _ 88",
		"Description": "Seaweed and fish",
		"ProductID": 46,
		"ProductName": "Spegesild",
		"SupplierID": 21,
		"QuantityPerUnit": "4 - 450 g glasses",
		"UnitPrice": 12,
		"UnitsInStock": 95,
		"UnitsOnOrder": 0,
		"ReorderLevel": 0,
		"Discontinued": false,
		"OrderID": 10390,
		"ProductName_Extended": "Spegesild",
		"UnitPrice_Extended": 9.6,
		"Quantity_Extended": 45,
		"Discount_Extended": 0,
		"ExtendedPrice": 432,
		"Subtotal": 2090.88,
		"CompanyName": "Lyngbysild",
		"ContactName": "Niels Petersen",
		"ContactTitle": "Sales Manager",
		"Address": "Lyngbysild Fiskebakken 10",
		"City": "Lyngby",
		"PostalCode": "2800",
		"Country": "Denmark",
		"Phone": "43844108",
		"Fax": "43844115"
	},
	{
		"CategoryID": 4,
		"CategoryName": "Dairy Products",
		"Description": "Cheeses",
		"ProductID": 72,
		"ProductName": "Mozzarella di Giovanni",
		"SupplierID": 14,
		"QuantityPerUnit": "24 - 200 g pkgs.",
		"UnitPrice": 34.8,
		"UnitsInStock": 14,
		"UnitsOnOrder": 0,
		"ReorderLevel": 0,
		"Discontinued": false,
		"OrderID": 10390,
		"ProductName_Extended": "Mozzarella di Giovanni",
		"UnitPrice_Extended": 27.8,
		"Quantity_Extended": 24,
		"Discount_Extended": 0.1,
		"ExtendedPrice": 600.48,
		"Subtotal": 2090.88,
		"CompanyName": "Formaggi Fortini s.r.l.",
		"ContactName": "Elio Rossi",
		"ContactTitle": "Sales Representative",
		"Address": "Viale Dante, 75",
		"City": "Ravenna",
		"PostalCode": "48100",
		"Country": "Italy",
		"Phone": "(0544) 60323",
		"Fax": "(0544) 60603",
		"HomePage": "#FORMAGGI.HTM#"
	},
	{
		"CategoryID": 3,
		"CategoryName": "Confections2",
		"Description": "Desserts, candies, and sweet breads 29",
		"ProductID": 47,
		"ProductName": "Zaanse koeken",
		"SupplierID": 22,
		"QuantityPerUnit": "10 - 4 oz boxes",
		"UnitPrice": 9.5,
		"UnitsInStock": 36,
		"UnitsOnOrder": 0,
		"ReorderLevel": 0,
		"Discontinued": false,
		"OrderID": 10585,
		"ProductName_Extended": "Zaanse koeken",
		"UnitPrice_Extended": 9.5,
		"Quantity_Extended": 15,
		"Discount_Extended": 0,
		"ExtendedPrice": 142.5,
		"Subtotal": 142.5,
		"CompanyName": "Zaanse Snoepfabriek",
		"ContactName": "Dirk Luchte",
		"ContactTitle": "Accounting Manager",
		"Address": "Verkoop Rijnweg 22",
		"City": "Zaandam",
		"PostalCode": "9999 ZZ",
		"Country": "Netherlands",
		"Phone": "(12345) 1212",
		"Fax": "(12345) 1210"
	},
	{
		"CategoryID": 8,
		"CategoryName": "Seafood _ 88",
		"Description": "Seaweed and fish",
		"ProductID": 10,
		"ProductName": "Ikura",
		"SupplierID": 4,
		"QuantityPerUnit": "12 - 200 ml jars",
		"UnitPrice": 31,
		"UnitsInStock": 31,
		"UnitsOnOrder": 0,
		"ReorderLevel": 0,
		"Discontinued": false,
		"OrderID": 10612,
		"ProductName_Extended": "Ikura",
		"UnitPrice_Extended": 31,
		"Quantity_Extended": 70,
		"Discount_Extended": 0,
		"ExtendedPrice": 2170,
		"Subtotal": 5015,
		"CompanyName": "Tokyo Traders",
		"ContactName": "Yoshi Nagase",
		"ContactTitle": "Marketing Manager",
		"Address": "9-8 Sekimai Musashino-shi",
		"City": "Tokyo",
		"PostalCode": "100",
		"Country": "Japan",
		"Phone": "(03) 3555-5011"
	},
	{
		"CategoryID": 8,
		"CategoryName": "Seafood _ 88",
		"Description": "Seaweed and fish",
		"ProductID": 36,
		"ProductName": "Inlagd Sill",
		"SupplierID": 17,
		"QuantityPerUnit": "24 - 250 g  jars",
		"UnitPrice": 19,
		"UnitsInStock": 112,
		"UnitsOnOrder": 0,
		"ReorderLevel": 20,
		"Discontinued": false,
		"OrderID": 10612,
		"ProductName_Extended": "Inlagd Sill",
		"UnitPrice_Extended": 19,
		"Quantity_Extended": 55,
		"Discount_Extended": 0,
		"ExtendedPrice": 1045,
		"Subtotal": 5015,
		"CompanyName": "Svensk Sjöföda AB",
		"ContactName": "Michael Björn",
		"ContactTitle": "Sales Representative",
		"Address": "Brovallavägen 231",
		"City": "Stockholm",
		"PostalCode": "S-123 45",
		"Country": "Sweden",
		"Phone": "08-123 45 67"
	},
	{
		"CategoryID": 3,
		"CategoryName": "Confections2",
		"Description": "Desserts, candies, and sweet breads 29",
		"ProductID": 49,
		"ProductName": "Maxilaku",
		"SupplierID": 23,
		"QuantityPerUnit": "24 - 50 g pkgs.",
		"UnitPrice": 20,
		"UnitsInStock": 10,
		"UnitsOnOrder": 60,
		"ReorderLevel": 15,
		"Discontinued": false,
		"OrderID": 10612,
		"ProductName_Extended": "Maxilaku",
		"UnitPrice_Extended": 20,
		"Quantity_Extended": 18,
		"Discount_Extended": 0,
		"ExtendedPrice": 360,
		"Subtotal": 5015,
		"CompanyName": "Karkki Oy",
		"ContactName": "Anne Heikkonen",
		"ContactTitle": "Product Manager",
		"Address": "Valtakatu 12",
		"City": "Lappeenranta",
		"PostalCode": "53120",
		"Country": "Finland",
		"Phone": "(953) 10956"
	},
	{
		"CategoryID": 4,
		"CategoryName": "Dairy Products",
		"Description": "Cheeses",
		"ProductID": 60,
		"ProductName": "Camembert Pierrot",
		"SupplierID": 28,
		"QuantityPerUnit": "15 - 300 g rounds",
		"UnitPrice": 34,
		"UnitsInStock": 19,
		"UnitsOnOrder": 0,
		"ReorderLevel": 0,
		"Discontinued": false,
		"OrderID": 10612,
		"ProductName_Extended": "Camembert Pierrot",
		"UnitPrice_Extended": 45,
		"Quantity_Extended": 5,
		"Discount_Extended": 1,
		"ExtendedPrice": 0,
		"Subtotal": 5015,
		"CompanyName": "Gai pâturage",
		"ContactName": "Eliane Noz",
		"ContactTitle": "Sales Representative",
		"Address": "Bat. B 3, rue des Alpes",
		"City": "Annecy",
		"PostalCode": "74000",
		"Country": "France",
		"Phone": "38.76.98.06",
		"Fax": "38.76.98.58"
	},
	{
		"CategoryID": 1,
		"CategoryName": "Beverages",
		"Description": "Soft drinks, coffees, teas, beers, and ales",
		"ProductID": 76,
		"ProductName": "Lakkalikööri",
		"SupplierID": 23,
		"QuantityPerUnit": "500 ml",
		"UnitPrice": 18,
		"UnitsInStock": 57,
		"UnitsOnOrder": 0,
		"ReorderLevel": 20,
		"Discontinued": false,
		"OrderID": 10612,
		"ProductName_Extended": "Lakkalikööri",
		"UnitPrice_Extended": 18,
		"Quantity_Extended": 80,
		"Discount_Extended": 0,
		"ExtendedPrice": 1440,
		"Subtotal": 5015,
		"CompanyName": "Karkki Oy",
		"ContactName": "Anne Heikkonen",
		"ContactTitle": "Product Manager",
		"Address": "Valtakatu 12",
		"City": "Lappeenranta",
		"PostalCode": "53120",
		"Country": "Finland",
		"Phone": "(953) 10956"
	}
];

  private chartTypes = [
      {
          "name": 'Bar',
          "value": 'bar'
      },
      {
        "name": 'Column',
        "value": 'column'
      }
     ,
      {
          "name": 'Line',
         "value": 'line'
     }
    ,
     {
         "name": 'Area',
         "value": 'area'
     }
];
  
  getChartingData = function() {
    return this.chartData.slice();
  }

  getChartTypes = function() {
      return this.chartTypes.slice();
  }

}
